/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_AHB1ENR (*(volatile uint32_t *)0x40023830U)
#define GPIOA_MODER (*(volatile uint32_t *)0x40020000U)
#define GPIOA_ODR (*(volatile uint32_t *)0x40020014U)

#define GPIOAEN (1U << 0)
#define LD2_PIN 5U
#define LD2_MODER_MASK (3U << (LD2_PIN * 2U))
#define LD2_MODER_OUTPUT (1U << (LD2_PIN * 2U))

static void delay(void)
{
    for (volatile uint32_t i = 0; i < 1000000U; ++i) {
        __asm volatile ("nop");
    }
}

int main(void)
{
    RCC_AHB1ENR |= GPIOAEN;

    GPIOA_MODER = (GPIOA_MODER & ~LD2_MODER_MASK) | LD2_MODER_OUTPUT;

    for (;;) {
        GPIOA_ODR ^= (1U << LD2_PIN);
        delay();
    }
}
